### ISSUE TITLE
"Hover" Technique question

### ISSUE THREAD

**Issue by hobbycoder7** [camiloaa/duolingonextlesson#15]
https://blog.duolingo.com/whats-the-best-way-to-learn-with-duolingo/

Is there a way to adjust the algorithm variable to reproduce the above? Specifically so that the tree would look like [https://blog.duolingo.com/content/images/2020/08/Blog_Post_Hover.png](https://blog.duolingo.com/content/images/2020/08/Blog_Post_Hover.png)

Thank you.

**Comment by camiloaa** [comment]
Unfortunately, no. It was not designed like that, and it can't be easily adapted for that. I wrote it before duolingo presented their "hover" idea, and I was more interested in making it feel like spaced repetition.
