### ISSUE TITLE
script does not work on an unfinished tree 

### ISSUE THREAD

**Issue by alexseyk** [camiloaa/duolingonextlesson#3]
Uncaught TypeError: Cannot read property 'map' of undefined
[www.duolingo.com-1582815743441.log](https://github.com/camiloaa/duolingonextlesson/files/4262228/www.duolingo.com-1582815743441.log)
[www.duolingo.com-1582815853987.log](https://github.com/camiloaa/duolingonextlesson/files/4262232/www.duolingo.com-1582815853987.log)
[www.duolingo.com-1582815920315.log](https://github.com/camiloaa/duolingonextlesson/files/4262243/www.duolingo.com-1582815920315.log)

**Comment by camiloaa** [comment]
The script definitively works on unfinished trees. Its main purpose is actually helping to finish the tree in a more effective way. 

The problem you are experienced is most likely related to a problem with duolingo's local storage. Clean the storage and cookies and try again. 

If you still get the same error, can you please provide the following info:

- Which course you are using.
- Other scripts, if any.
- Output from running this code on the console.

``` js
function isCurrentCourse(x)
{
	return x.learningLanguage === duoState.user.learningLanguage &&
		x.fromLanguage === duoState.user.fromLanguage;
}

duoState = JSON.parse(localStorage['duo.state']);
console.debug("Total courses: " + Object.keys(duoState.courses).length);
course_skills = Object.values(duoState.skills).filter(isCurrentCourse);
console.debug("Total skills: " + course_skills.length);
skills = course_skills.filter(skill => skill.accessible == true &&
		skill.hasOwnProperty('bonus') == false);
current_course = Object.values(duoState.courses).filter(isCurrentCourse);
console.debug("Total matching courses: " + current_course.length);
```

**Comment by alexseyk** [comment]
My apologies 
I cleared history & it worked
