### ISSUE TITLE
lesson count not displayed 

### ISSUE THREAD

**Issue by alexseyk** [camiloaa/duolingonextlesson#6]
for bonus skills in en<>es tree
for skill 19 & 20 in en<ru tree 
[bonus es en.log](https://github.com/camiloaa/duolingonextlesson/files/4262498/bonus.es.en.log)
[lessons 19 20 en ru.log](https://github.com/camiloaa/duolingonextlesson/files/4262499/lessons.19.20.en.ru.log)

**Comment by camiloaa** [comment]
Bonus skills are not supported. I don't know why, but Duolingo seems to treat them very differently to other skills, and they are just not worth it for me.

**Comment by alexseyk** [comment]
ok, forget about bonus skills, what about others ?
<img width="1349" alt="Screen Shot 2020-03-03 at 10 09 28" src="https://user-images.githubusercontent.com/60418150/75739299-1f6c5800-5d37-11ea-97d2-d62e38f91c13.png">

**Comment by camiloaa** [comment]
I can't reproduce.

![Screenshot_2020-03-03 Learn a language for free](https://user-images.githubusercontent.com/2361161/75760792-247dd700-5d38-11ea-96d2-063e3d0f25f4.png)

 Are you sure you're running the latest version 1.2.4? Duolingo changes the UI components from time to time, breaking the script.

**Comment by alexseyk** [comment]
This is in the English FROM Russian tree ONLY for skills  # 19 and 20. 
If i see the same problem  in my other trees i'll let you know 
I just updated from 1.2.3 to 1.2.4 after clearing browser history etc problem is still there. 
same error.
userscript.html?id=a1259e01-602f-4872-bcc8-b7af1da9100d:303 Uncaught TypeError: Cannot read property 'finishedLessons' of undefined
    at MutationObserver.onChangeNextLesson (userscript.html?id=a1259e01-602f-4872-bcc8-b7af1da9100d:303)

**Comment by camiloaa** [comment]
Are those two the only skills with a '?' in their name? It might be an encoding problem. Can you check skills 16 and 32?

**Comment by alexseyk** [comment]
Привет!

Я зелёный совёнок Duo! Добро пожаловать на Duolingo, самое скачиваемое образовательное приложение в мире!

    Вот два совета, как учить английский эффективнее.

1. Загрузите приложение Duolingo
Учитесь в любое время и в любом месте.

2. Занимайтесь каждый день
5-10 минут в день — и вы заведете полезную привычку, которая изменит вашу жизнь.

5900 Penn Avenue, Pittsburgh PA 15206, USA
Отказ от уведомлений

**Comment by alexseyk** [comment]
16 & 32 are fine, and the rest too, just 19 & 20 are no  good

i made an account for you : UID & PWD the same - NextLesson
Please take a look  yourself and delete it when done.

**Comment by camiloaa** [comment]
Thank you! Definitively an encoding problem. Fixed.

**Comment by alexseyk** [comment]
Hi NextLesson! Keep Duo happy! Remember that learning a language requires a little bit of practice every day.
===========================================

Keep going to reach your next target
45 points away from level 2



If you'd rather not receive notifications, you can unsubscribe in
https://www.duolingo.com/unsubscribe?email=e260ec30beeb90ab15922dc22ea00bd98d30d16aInJlcGx5K0FPTTZRWlcyT1ZTUkVNS1lMNkxaNjNWNE5JNlpORVZCTkhIQ0VHVlo2SUByZXBseS5naXRodWIuY29tIg==&type=notify_practice&language_abbrev=es

(c) 2020 Duolingo
5900 Penn Avenue
Pittsburgh PA 15206
USA
